services:
  # The Memory: Database
  db:
    image: postgres:15
    container_name: standard_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # You can change this later
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # The Brain: Automation (n8n)
  n8n:
    image: n8nio/n8n:latest
    container_name: standard_brain
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_PROTOCOL=https
    volumes:
      - ./flows:/home/node/.n8n
      - ./public/images:/home/node/.n8n-files/public/images
      - ./n8n-workflows:/home/node/.n8n-files/workflows
    depends_on:
      db:
        condition: service_healthy

  image_server:
    image: nginx:alpine
    ports:
      - "8082:80"  # We'll use port 8081 to avoid conflicts
    volumes:
      - ./public/images:/usr/share/nginx/html/images:ro # 'ro' means read-only for safety

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from overwriting container ones
    environment:
      - VITE_GET_PRODUCTS_WEBHOOK=${GET_PRODUCTS_WEBHOOK}
      - VITE_IMAGE_BASE_URL=${IMAGE_BASE_URL}
      - VITE_RECORD_SALES_WEBHOOK=${RECORD_SALES_WEBHOOK}
      - VITE_DAILY_SALES_WEBHOOK=${DAILY_SALES_WEBHOOK}
      - VITE_CURRENCY=${CURRENCY}
      - VITE_APP_TITLE=${VITE_APP_TITLE}
      - VITE_APP_ICON=${VITE_APP_ICON}
    depends_on:
      - n8n
      - image_server
  
    