server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /accounting {
        return 301 /accounting/;
    }

    location /accounting/ {
        try_files $uri $uri/ /accounting/index.html;
    }
}