name: Deploy to Server
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from JSON
        run: |
          echo '${{ secrets.ENV_JSON }}' \
            | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > .env
          echo ".env created:"
          cat .env

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Copy .env and deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_NAME: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

          # Copy .env
          # Correct path for system root folder
          scp .env $USER_NAME@$SERVER_IP:/root/app_tmp/.env


          # SSH into server and deploy
          ssh $USER_NAME@$SERVER_IP "
            if [ ! -d .git ]; then
              git clone -b staging git@github.com:DamienBarnesAutomations/commerce-flow-project.git /app
            else
              git pull
            fi
            mv /root/app_tmp/.env /root/app/

            cd app
            docker compose up --build -d
          "